# Generated by Django 4.2.5 on 2023-09-26 15:10

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media_image",
            field=models.ImageField(
                null=True, upload_to=user.models.post_image_file_path
            ),
        ),
    ]
